apiVersion: v1
kind: Service
metadata:
  name: mongodb-internal
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    name: "mongodb"
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    name: "mongodb"
