apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mongodb
  name: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  type: ClusterIP
status:
  loadBalancer: {}
